cartapp/urls.py
from django.urls import path, include
from . import views
app_name = 'cartapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('film/<int:film_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

filmcart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cartapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cartapp/models.py
from django.db import models


# Create your models here.
class FilmDetail(models.Model):
    film_name = models.CharField(max_length=250)
    film_desc = models.TextField()
    film_year = models.IntegerField()
    film_icon = models.ImageField()

    def __str__(self):
        return self.film_name

cartapp/forms.py
from django import forms
from .models import FilmDetail


class film_form(forms.ModelForm):
    class Meta:
        model = FilmDetail
        fields = ['film_name', 'film_desc', 'film_year', 'film_icon']

cartapp/views.py
from django.shortcuts import render, redirect
from .models import FilmDetail
from .forms import film_form


# Create your views here.
def index(request):
    films = FilmDetail.objects.all()
    context = {'film_list': films}
    return render(request, 'index.html', context)


def detail(request, film_id):
    films = FilmDetail.objects.get(id=film_id)
    return render(request, 'detail.html', {'films': films})


def add_movie(request):
    if request.method == 'POST':
        film_name = request.POST.get('film_name')
        film_desc = request.POST.get('film_desc')
        film_year = request.POST.get('film_year')
        film_icon = request.FILES.get('film_icon')
        films = FilmDetail(film_name=film_name, film_desc=film_desc, film_year=film_year, film_icon=film_icon)
        films.save()
    return render(request, 'add.html')


def update(request, id):
    films = FilmDetail.objects.get(id=id)
    form = film_form(request.POST or None, request.FILES, instance=films)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'form': form, 'films': FilmDetail})


def delete(request, id):
    if request.method == 'POST':
        film = FilmDetail.objects.get(id=id)
        film.delete()
        return redirect('/')
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="post" enctype="multipart/form-data" style="text-align:center">
  {% csrf_token %}
  <input type="text" placeholder="Enter the name of the movie" name="film_name"><br><br>
  <input type="text" name="film_desc" placeholder="Enter the description"><br><br>
  <input type="text" name="film_year" placeholder="Enter the year"><br><br>
  <input type="file" name="film_icon"><br><br>
  <input type="submit"><br><br>

</form>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="http://127.0.0.1:8000/">Film Cart</a>
    <a class="navbar-brand" href="{% url 'cartapp:add' %}">ADD</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  Are you sure to delete ..?
  <input type="submit">
</form>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <img class="card-img-top" src="{{films.film_icon.url}}" height="270">
                <div class="card-body">
                    <a class="btn btn-danger" href="{% url 'cartapp:update' films.id %}">Update</a>
                    <a class="btn btn-danger" href="{% url 'cartapp:delete' films.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <h5>Name of the Movie:  </h5>{{films.film_name}}<br>
            <h5>Description of the Movie </h5>{{films.film_desc}}<br>
            <h5>Name of the Year </h5>{{films.film_year}}<br><br>
            <a class="btn btn-warning" href="http://127.0.0.1:8000/">Home</a>
        </div>
    </div>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in film_list %}
        <div class="col-md-3">
            <div class="card">
                <img class="card-img-top" src="{{i.film_icon.url}}" alt="Card image cap" height="270">
                <div class="card-body">
                    <h5 class="card-title">{{i.film_name}}</h5>
                    <p class="card-text">{{i.film_desc}}</p>
                    <a href="{% url 'cartapp:detail' i.id %}" class="btn btn-primary">Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

{% endblock %}